checkpoints_path: "./assistant_data"

# sentence-transformers/all-MiniLM-L6-v2
# jinaai/jina-embeddings-v2-base-code
embedding_model_name: "jinaai/jina-embeddings-v2-base-code"
llm_model_name: "qwen/qwen-2.5-coder-32b-instruct:free"
project_path: "./"
file_extensions:
  - ".py"
ignore_dirs:
  - "assistant_data"
  - "venv"
  - ".venv"
  - ".git"
  - ".vscode"
  - "__pycache__"
  - "node_modules"
  - "build"
  - "dist"
  - "__OLD__"